import { Feature, PricingPlan, Testimonial, NavItem, CommandItem } from "@/types/family";

export const NAV_ITEMS: NavItem[] = [
  { label: "Features", href: "/#features" },
  { label: "Demo", href: "/#demo" },
  { label: "Pricing", href: "/#pricing" },
  { label: "Timeline", href: "/timeline" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const FEATURES: Feature[] = [
  {
    id: "unlimited-members",
    title: "Unlimited Family Members",
    description: "Add every branch of your family tree, no matter how large. Connect generations across centuries with no limits.",
    icon: "Users",
    badge: "Core",
  },
  {
    id: "beautiful-profiles",
    title: "Beautiful Family Profiles",
    description: "Each member gets a rich profile with photos, bio, achievements, and life story — a true digital legacy.",
    icon: "UserCircle",
  },
  {
    id: "shareable-cards",
    title: "Shareable Family Cards",
    description: "Generate stunning, Spotify Wrapped-style family cards to share your legacy with the world.",
    icon: "Share2",
    badge: "Popular",
  },
  {
    id: "import-csv",
    title: "Import from CSV",
    description: "Already have your family data somewhere? Import it instantly with our smart CSV importer.",
    icon: "FileUp",
  },
  {
    id: "export-pdf",
    title: "Export as PDF",
    description: "Download your complete family tree as a beautifully formatted PDF to print and preserve forever.",
    icon: "FileDown",
  },
  {
    id: "qr-sharing",
    title: "QR Code Sharing",
    description: "Generate a unique QR code for your family tree. Share it at weddings, reunions, and family events.",
    icon: "QrCode",
    badge: "New",
  },
  {
    id: "family-timeline",
    title: "Family Timeline",
    description: "Visualize your family's entire history as a beautiful, scrollable timeline of births, marriages, and achievements.",
    icon: "Timeline",
  },
  {
    id: "photo-albums",
    title: "Photo Albums",
    description: "Preserve precious family memories with curated photo albums organized by era, event, or family member.",
    icon: "Image",
  },
  {
    id: "role-management",
    title: "Role Management",
    description: "Control who can view, edit, or manage your family tree with granular permission settings.",
    icon: "Shield",
  },
  {
    id: "private-sharing",
    title: "Private Sharing",
    description: "Share your family tree privately with trusted family members using invite-only access links.",
    icon: "Lock",
  },
  {
    id: "interactive-tree",
    title: "Interactive Visual Tree",
    description: "Experience your family history as a living, interactive graph — zoom, pan, and explore generations.",
    icon: "GitBranch",
    badge: "Core",
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Seedling",
    price: 0,
    period: "forever",
    description: "Perfect for getting started with your family story.",
    cta: "Start Free",
    features: [
      "Up to 25 family members",
      "Basic family tree view",
      "5 photo uploads",
      "Public profile page",
      "QR code sharing",
      "CSV import",
    ],
  },
  {
    id: "family",
    name: "Heritage",
    price: 299,
    period: "per month",
    description: "For families serious about preserving their legacy.",
    cta: "Start Heritage",
    isPopular: true,
    features: [
      "Unlimited family members",
      "Interactive React Flow tree",
      "Unlimited photo albums",
      "PDF export",
      "Family timeline",
      "Private sharing",
      "Role management",
      "Priority support",
      "Shareable family cards",
    ],
  },
  {
    id: "legacy",
    name: "Legacy",
    price: 799,
    period: "per month",
    description: "The complete family heritage platform for generations.",
    cta: "Start Legacy",
    features: [
      "Everything in Heritage",
      "Custom family domain",
      "DNA integration (coming soon)",
      "Dedicated family historian",
      "White-glove data import",
      "Printed family book annually",
      "API access",
      "Advanced analytics",
      "Multi-language support",
      "24/7 priority support",
    ],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    name: "Anita Krishnamurthy",
    location: "Chennai, Tamil Nadu",
    avatar: "https://api.dicebear.com/7.x/personas/svg?seed=anita&backgroundColor=ffd5dc",
    quote: "Vanshavali has been a revelation for our family. We discovered relatives we didn't know existed, and my 80-year-old mother cried when she saw her late husband's profile. This is not just a product — it's a time machine.",
    rating: 5,
    familySize: 87,
  },
  {
    id: "t2",
    name: "Rajiv Mehta",
    location: "Ahmedabad, Gujarat",
    avatar: "https://api.dicebear.com/7.x/personas/svg?seed=rajiv&backgroundColor=b6e3f4",
    quote: "I spent years trying to document our family history in spreadsheets. Vanshavali replaced all of that in an afternoon. The family tree visualization is absolutely breathtaking — I showed it at our family reunion and everyone was amazed.",
    rating: 5,
    familySize: 134,
  },
  {
    id: "t3",
    name: "Preethi Subramanian",
    location: "Bengaluru, Karnataka",
    avatar: "https://api.dicebear.com/7.x/personas/svg?seed=preethi&backgroundColor=d1f7c4",
    quote: "The shareable family card feature is genius. I send it to relatives during Diwali and they love it. My NRI cousins in the US use Vanshavali to stay connected to their roots. The design is just so elegant — nothing like other genealogy tools.",
    rating: 5,
    familySize: 62,
  },
];

export const COMMAND_ITEMS: CommandItem[] = [
  {
    id: "cmd-tree",
    label: "View Family Tree",
    description: "Open the interactive family tree",
    icon: "GitBranch",
    action: "/tree",
    shortcut: "G T",
    category: "Navigation",
  },
  {
    id: "cmd-timeline",
    label: "Open Timeline",
    description: "View the family timeline",
    icon: "Clock",
    action: "/timeline",
    shortcut: "G L",
    category: "Navigation",
  },
  {
    id: "cmd-card",
    label: "Generate Family Card",
    description: "Create a shareable family card",
    icon: "Share2",
    action: "/card",
    shortcut: "G C",
    category: "Actions",
  },
  {
    id: "cmd-about",
    label: "About Vanshavali",
    description: "Learn about our mission",
    icon: "Info",
    action: "/about",
    category: "Navigation",
  },
  {
    id: "cmd-contact",
    label: "Contact Us",
    description: "Get in touch with our team",
    icon: "Mail",
    action: "/contact",
    category: "Navigation",
  },
  {
    id: "cmd-dark",
    label: "Toggle Dark Mode",
    description: "Switch between light and dark theme",
    icon: "Moon",
    action: "theme-toggle",
    shortcut: "⌘ D",
    category: "Preferences",
  },
  {
    id: "cmd-export",
    label: "Export Family PDF",
    description: "Download your family tree as PDF",
    icon: "FileDown",
    action: "export-pdf",
    category: "Actions",
  },
  {
    id: "cmd-share",
    label: "Share Family Tree",
    description: "Copy shareable link to clipboard",
    icon: "Link",
    action: "copy-link",
    category: "Actions",
  },
];

export const STATS = [
  { value: 12847, label: "Families Preserved", suffix: "+" },
  { value: 4, label: "Generations Connected", suffix: "M+" },
  { value: 98, label: "Satisfaction Rate", suffix: "%" },
  { value: 847, label: "Cities Across India", suffix: "+" },
];
